### ISSUE TITLE
Feature - Toolbar button

### ISSUE THREAD

**Issue by imtrobin** [Naotsun19B/GraphPrinter#2]
Hi, can you add it to toolbar instead of shortcut keys.

**Comment by Naotsun19B** [comment]
I don't think it's very realistic because there are various graph editors and you have to add a toolbar to each of them.
I apologize for the inconvenience.

**Comment by Naotsun19B** [comment]
I'm sorry to have kept you waiting for a long time.
With this update (version 2.1), you can now perform functions from the toolbar.
Please update the plugin and try it.
