### ISSUE TITLE
NewFeature - White background for print

### ISSUE THREAD

**Issue by bina654** [Naotsun19B/GraphPrinter#4]
hi, 
I've been looking for this plugin for a long time! thank you so much for this
I like to have everything on paper for personal organization issues it would be perfect if you could make take the print without the gray background just the blueprints with a white or transparent background. in addition to being more noticeable, we don't waste so much toner :)

**Comment by Naotsun19B** [comment]
Thank you for using my plugin.
It is very helpful to have your feedback.
I have been aware of that bug for some time and have put in several responses, but depending on the environment, version, and timing, it does not seem to have been fixed.
I will continue to investigate and improve the issue, but it is probably difficult to improve it completely, so I would appreciate it if you could re-run the output again when the problem occurs.
I apologize for any inconvenience this may cause, and I look forward to your continued use of my plugins.
